### ISSUE TITLE
Remove RFN

### ISSUE THREAD

**Issue by davelab6** [rayshan/mplus-fonts#1]
I suggest changing the copyright notice to

```
Copyright (c) 2002-2015 Coji Morishita 森下浩司 (co@underforest.com)
```

and making the license file otherwise the same as https://github.com/google/fonts/blob/master/ofl/hind/OFL.txt including filename

**Comment by rayshan** [comment]
Closed by https://github.com/rayshan/mplus-fonts/commit/bed5ec777b1994526bbd09d39575c009456a3508

The reason I left RFN in there is because some fonts currently in the Google Fonts repo also have that, e.g.: https://github.com/google/fonts/blob/master/ofl/lato/OFL.txt

**Comment by davelab6** [comment]
Yeah I discourage it, it is grandfathered in to some families
